name: 591 Days
favicon: null
layout_spectrum: 0.50978
typography_spectrum: 0.75636
title: 591 Days
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71895836-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2a2730'
    - '#e24892'
    - '#21b9d0'
    - '#feb9fe'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
