name: 591 Days
favicon: null
layout_spectrum: 0.776361619355157
typography_spectrum: 0.33472876995801926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.49650189792737365
  lightness: 0.46384273981675506
  saturation: 0.8259058503899723
  rhythmicContrast: 0.7491714030038565
purpose: []
